language: node_js
node_js:
  - 10
before_install:
  - yarn global add @vue/cli
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  fqdn: games.salad242.gq
  on:
    branch: master
